DROP TABLE IF EXISTS users;

CREATE TABLE users(
   ID INT SERIAL PRIMARY KEY NOT NULL,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(50) NOT NULL,
   email VARCHAR(50) UNIQUE NOT NULL,
   password  VARCHAR(50) NOT NULL
);